### ISSUE TITLE
代码测试

### ISSUE THREAD

**Issue by Archeb** [Archeb/archeb.github.io#5]
```css
@font-face {
  font-family: Chunkfive; src: url('Chunkfive.otf');
}

body, .usertext {
  color: #F0F0F0; background: #600;
  font-family: Chunkfive, sans;
}

@import url(print.css);
@media print {
  a[href^=http]::after {
    content: attr(href)
  }
}
```

从HLJS官网抄的一份CSS奉上
